# BERT Demo

## References 

https://www.tensorflow.org/hub

https://tfhub.dev/google/collections/bert/1

https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4

https://www.youtube.com/c/codebasics

## Loading Libraries

In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

## Loading Urls

encoder and preprocessing url

In [2]:
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"
preprocessing_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"

## Loading BERT Preprocessor

In [3]:
preprocessor = hub.KerasLayer(preprocessing_url)

### testing preprocessor

In [5]:
test_text = [
    "this is first document",
    "I love pasta"
]

test_dict = preprocessor(test_text)
test_dict.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

Preprocessor returns a dictionary with 3 values. 

- input_word_ids : has the token ids of the input sequences.
- input_mask : has value 1 at the position of all input tokens present before padding and value 0 for the padding tokens.
- input_type_ids : has the index of the input segment that gave rise to the input token at the respective position. The first input segment (index 0) includes the start-of-sequence token and its end-of-segment token. The second segment (index 1, if present) includes its end-of-segment token. Padding tokens get index 0 again.


every sentence/row has prefix `CLS` and suffix `SEP`.

In [9]:
test_dict['input_word_ids'].shape

TensorShape([2, 128])

`CLS this is first document SEP`

In [13]:
test_dict['input_word_ids'][0]

<tf.Tensor: shape=(128,), dtype=int32, numpy=
array([ 101, 2023, 2003, 2034, 6254,  102,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)>

In [14]:
test_dict['input_mask'].shape


TensorShape([2, 128])

In [15]:
test_dict['input_mask'][0]


<tf.Tensor: shape=(128,), dtype=int32, numpy=
array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

In [16]:
test_dict['input_type_ids'].shape

TensorShape([2, 128])

In [20]:
test_dict['input_type_ids'][0]


<tf.Tensor: shape=(128,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

## Loading Encoder 

In [26]:
encoder_model = hub.KerasLayer(encoder_url)

### testing encoder

In [28]:
encoded_dict = encoder_model(test_dict)

In [29]:
encoded_dict.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [30]:
encoded_dict['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8564542 , -0.20264098,  0.44491994, ...,  0.18142326,
        -0.52242935,  0.839577  ],
       [-0.8231588 , -0.19543926,  0.4399575 , ...,  0.3558046 ,
        -0.5919596 ,  0.8541847 ]], dtype=float32)>

In [31]:
encoded_dict['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-2.23829597e-01,  2.58546323e-01,  1.60378978e-01, ...,
         -1.75076678e-01,  2.57635832e-01,  3.58420372e-01],
        [-5.81663609e-01, -2.24008322e-01,  6.07548207e-02, ...,
         -4.35946345e-01,  7.22116292e-01,  2.05105364e-01],
        [-5.88114560e-01, -3.27617466e-01,  6.20402157e-01, ...,
         -4.78888750e-01,  5.28291821e-01,  6.42452359e-01],
        ...,
        [-2.36085236e-01,  1.05683051e-01,  5.52026212e-01, ...,
          1.31120771e-01,  4.79894549e-01,  3.75098825e-01],
        [-2.66874582e-01,  8.43454301e-02,  5.48812032e-01, ...,
          1.94243729e-01,  4.29042369e-01,  3.45293581e-01],
        [-3.05021435e-01,  4.44966406e-02,  5.43690860e-01, ...,
          2.48683482e-01,  4.10975337e-01,  2.66701370e-01]],

       [[ 8.02702308e-02,  2.39341095e-01,  6.48294538e-02, ...,
         -2.08112523e-01,  1.62344888e-01,  2.63515770e-01],
        [ 1.01238646e-01,  2.56397724e-01,  1.76

In [32]:
encoded_dict['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 1.47699326e-01, -5.29840589e-03, -4.65565994e-02, ...,
           4.89456207e-02,  1.48127392e-01,  2.66219191e-02],
         [-3.29997718e-01,  5.69829226e-01,  4.65500951e-02, ...,
           2.88064405e-02,  7.90993929e-01,  7.87367448e-02],
         [-9.17791724e-01, -3.76092851e-01, -5.89847803e-01, ...,
          -6.70608878e-03,  9.09315884e-01,  5.67392647e-01],
         ...,
         [ 1.03799485e-01, -2.44910002e-01,  5.11505842e-01, ...,
           1.68316975e-01, -1.90354049e-01,  7.36336038e-02],
         [ 1.73913762e-02, -2.50474840e-01,  4.13143516e-01, ...,
           1.95029616e-01, -8.89173597e-02, -4.88333404e-04],
         [ 1.59129798e-01, -1.92517638e-01,  4.12100226e-01, ...,
           5.27291179e-01, -3.84005874e-01, -9.34847221e-02]],
 
        [[ 1.69877589e-01,  6.36416972e-02, -9.08207819e-02, ...,
           1.72630399e-02,  1.21654108e-01,  4.03790362e-02],
         [ 5.80580592e-01,  1.1